### ISSUE TITLE
Consider renaming to go-ipns-record

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipns#1]
This package doesn't contain resolution logic. We'll probably want a package containing a value store based resolver/publisher and `go-ipns` may be the right place for that.

**Comment by vasco-santos** [comment]
As discussed in the `js-ipfs` [PR feat: IPNS](https://github.com/ipfs/js-ipfs/pull/1400#issuecomment-399558714), I totally agree with this rename.

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant.
