### ISSUE TITLE
IPNS directories being empty after new file being added

### ISSUE THREAD

**Issue by matthew-mcateer** [ipfs/go-ipns#15]
So recently, I published a directory to IP**N**S then added a file to the directory. After I checked IP**N**S again, the file did not show up. I know that with IP**F**S it behaves similarly to version control; the hash is different each time the contents of the directory are changed. My understanding with IP**N**S was that this was supposed to be a way of more stably pining directories to a single hash identity (correct me if I'm mistaken). 

Basically, I've been trying to create an application with an IPNS-based back-end. The previous back-end was previously made with Node.js and MongoDB, and the front-end connected through a localhost gateway. I've been attempting to at least get a stable read-only version of this web app where a nested directory on IPFS/IPNS behaves similarly enough to an API spec.

(NOTE: please let me know if there is any other information you would prefer about this problem. I can add the specific commands and files that were used as well. If you want to see the full documentation of the API spec I'm trying to replicate, I can add that as well. I just didn't want to prematurely cause information overload)

**Comment by Stebalien** [comment]
So, when you add a file to an IPFS directory, you get a new directory. However, the the IPNS entry will continue pointing to the old directory until you update it to point it to the new one. We do have some logic to do this automatically, but it only works with the FUSE mounted /ipns/local directory and we generally don't recommend the FUSE mounts as they tend to be a bit buggy and unloved.

(also note, if you add a directory to IPFS and then add a file to the directory in your normal filesystem, that file won't automatically get added to IPFS)

**Comment by matthew-mcateer** [comment]
Thank you @Stebalien. We've been trying out FUSE, as well as setting up our own local directory. Where specifically could one find this logic for doing this automatically. Is it in this particular repo?

And we had made that mistake with IPFS early on (regarding adding it to the directory on our system but not on IPFS), but we've corrected for that. Thanks for the reminder though. I get the sense that with debudding IPFS issues, that's been the equivalent of "have you tried turning your system off and on again" what works suprisingly well.

**Comment by Stebalien** [comment]
> Is it in this particular repo?

No, this repo just contains some shared logic for creating and validating IPNS records. Most of the logic is still in go-ipfs. Specifically, https://github.com/ipfs/go-ipfs/blob/336520d4ef0d06ac28b6e6c189c3d4c099b1ba38/fuse/ipns/ipns_unix.go#L114

However, I'm not sure how much that'll help you.

---

Personally, I'd recommend:

1. Managing files using the `ipfs files` commands. This command allows you to manage files in a virtual, mutable filesystem.
2. Manually publishing by running: `ipfs name publish $(ipfs files stat --hash /path/to/file/in/your/virtual/file/system)`.

Again, you can also use the FUSE mount and it should just work but it's not very well maintained.

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue is no longer relevant, and therefore is being closed.
