### ISSUE TITLE
Needs Review

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipns#2]
This package should be thoroughly reviewed. To make it a bit more general-purpose (less libp2p-record specific), I've refactored it quite a bit.

**Comment by schomatis** [comment]
@Stebalien Could you provide me some more context here please?

**Comment by Stebalien** [comment]
This is an extraction of the IPNS record creation, validation, and sorting logic. This way:

1. Packages don't have to pull in all of go-ipfs just to validate IPNS records. E.g., [dht-node](https://github.com/ipfs/dht-node/pull/3).
2. Users/developers trying to understand IPNS don't have to fish around the go-ipfs repo.

---

I assigned you because you tend to be very thorough and this code has been historically tricky to get right. Feel free to unassign yourself if you feel you don't have enough context/background with IPNS or feel strapped for time. Also, this isn't exactly pressing.

**Comment by postables** [comment]
Personally I love this package, and have already started using it. It has been so much easier to use this instead of digging around the go-ipfs repo

**Comment by Stebalien** [comment]
@postables thanks!

**Comment by dirkmc** [comment]
Agreed, this is much better. Excited that you're making a big effort to improve IPNS @Stebalien and @whyrusleeping

**Comment by schomatis** [comment]
I'm (temporarily) unassigning myself from this issue due to my lack of knowledge (and documentation) about IPNS, if someone want to take it go ahead, if not I'll came back when I'm better prepared for it.

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue has been moved to https://github.com/ipfs/boxo/issues/335.
