### ISSUE TITLE
stop using peer.IDFromString

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/go-ipns#37]
`peer.IDFromString` was removed from libp2p, as it is almost always used incorrectly, see https://github.com/libp2p/go-libp2p-core/pull/274.

This repo uses it in https://github.com/ipfs/go-ipns/blob/500f0a86cb9e7457ff66eacc852eb9ae40f9e4b9/record.go#L49

I'm not 100% sure if it's used correctly here or not, so I can't submit a fix. This needs to be resolved before we can update the IPFS stack to go-libp2p v0.22.0.

**Comment by lidel** [comment]
I believe the `pidString` is  binary:

- https://github.com/ipfs/specs/blob/main/IPNS.md#routing-record defines Routing record as `/ipns/BINARY_ID` 
- pidString is the binary part:
  https://github.com/ipfs/go-ipns/blob/500f0a86cb9e7457ff66eacc852eb9ae40f9e4b9/record.go#L36
  
So we want `peer.IDFromBytes([]byte(pidString))`  here. Mind opening a fix @marten-seemann?
